/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
export namespace Components {
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppRoot {
    }
    interface AppUsersList {
    }
    interface FaI {
        "icon": IconDefinition;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppUsersListElement extends Components.AppUsersList, HTMLStencilElement {
    }
    var HTMLAppUsersListElement: {
        prototype: HTMLAppUsersListElement;
        new (): HTMLAppUsersListElement;
    };
    interface HTMLFaIElement extends Components.FaI, HTMLStencilElement {
    }
    var HTMLFaIElement: {
        prototype: HTMLFaIElement;
        new (): HTMLFaIElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-root": HTMLAppRootElement;
        "app-users-list": HTMLAppUsersListElement;
        "fa-i": HTMLFaIElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppRoot {
    }
    interface AppUsersList {
    }
    interface FaI {
        "icon"?: IconDefinition;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-root": AppRoot;
        "app-users-list": AppUsersList;
        "fa-i": FaI;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-users-list": LocalJSX.AppUsersList & JSXBase.HTMLAttributes<HTMLAppUsersListElement>;
            "fa-i": LocalJSX.FaI & JSXBase.HTMLAttributes<HTMLFaIElement>;
        }
    }
}
